---
- name: Gather OS specific variables for Composer
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"

- name: Install required packages
  package:
    name: "{{ composer_package }}"
    state: present
  tags:
    - packages

- name: Install Composer from source
  become: true
  get_url:
    url: "{{ composer_url }}"
    dest: "{{ composer_executable }}"
    mode: 0755
    checksum: "{{ composer_checksum }}"
    group: root
    owner: root
  when: composer_package|length == 0
